## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
after_success:
  # Push coverage results to Codecov.
  - julia -e 'cd(Pkg.dir("FDM")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # Build docs.
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("FDM")); include(joinpath("docs", "make.jl"))'
