name: IntegrationTestChainRules 
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  test:
    name: Julia v${{ matrix.julia-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: x64
      - uses: julia-actions/julia-buildpkg@latest
      - name: Clone ChainRules
        uses: actions/checkout@v2
        with:
          repository: JuliaDiff/ChainRules.jl
          path: "ChainRules.jl"
      - name: Run the tests
        run: |
          julia -e "p = \"ChainRules.jl/Project.toml\"; toml = TOML.parsefile(p); delete!(toml[\"compat\"], \"FiniteDifferences\"); open(io -> TOML.print(io, toml), p, \"w\")"
          julia --project="ChainRules.jl" -e "using Pkg; Pkg.develop(PackageSpec(path=\"./\")); Pkg.update(); Pkg.test()"
        shell: bash
